version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
  kibana:
    depends_on:
      - "elasticsearch"
    image: docker.elastic.co/kibana/kibana:7.8.1
    ports:
      - "5601:5601"
    links:
      - "elasticsearch"
